#SPDX-License-Identifier: MIT-0
---
- name: Install unzip for extracting Alertmanager
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Create Alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    system: yes
    shell: /bin/false
    home: "{{ alertmanager_data_dir }}"
    create_home: no

- name: Create Alertmanager configuration directory
  file:
    path: "{{ alertmanager_config_dir }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: '0755'

- name: Create Alertmanager data directory
  file:
    path: "{{ alertmanager_data_dir }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: '0755'

- name: Download Alertmanager
  get_url:
    url: "{{ alertmanager_download_url }}"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    mode: '0644'

- name: Extract Alertmanager
  unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy Alertmanager binaries
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
    dest: "{{ alertmanager_binary_dir }}/{{ item }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: '0755'
    remote_src: yes
  loop:
    - alertmanager
    - amtool

- name: Copy Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: '0644'
  notify: Restart Alertmanager

- name: Create Alertmanager systemd service
  copy:
    dest: "{{ alertmanager_service_file }}"
    content: |
      [Unit]
      Description=Prometheus Alertmanager
      Wants=network-online.target
      After=network-online.target

      [Service]
      User={{ alertmanager_user }}
      Group={{ alertmanager_group }}
      Type=simple
      ExecStart={{ alertmanager_binary_dir }}/alertmanager \
        --config.file={{ alertmanager_config_dir }}/alertmanager.yml \
        --storage.path={{ alertmanager_data_dir }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  notify: Restart Alertmanager

- name: Ensure Alertmanager service is enabled and started
  systemd:
    name: alertmanager
    enabled: yes
    state: started

- name: Clean up Alertmanager tarball
  file:
    path: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    state: absent

- name: Clean up Alertmanager extracted directory
  file:
    path: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64"
    state: absent
